---
title: "Relative Abundance and Bubble plots"
output: html_notebook
---

# Relative Abundance and Bubble Plots
Relative abundance plots vs bubble plots

## load packages
```{r}
library("ggplot2")
library("phyloseq")
library("RColorBrewer")
library("reshape2")
library("nlme")
library("dplyr")
library("compositions")
library("tidyverse")
```

## load the files needed
```{r}
ps <- readRDS("examplePhyloseq.rds") #import the .rds phyloseq object made in the intro to phyloseq notebook
ps #confirm it worked
```

## Relative Abundance plots
What goes in:
What goes out:
```{r}
physeq.f <- filter_taxa(ps, function(x) sum(x >= 100) > (0.01*length(x)), prune = TRUE) #filter out super small numbers
physeq.f #check it worked
head(sample_data(physeq.f)) #just checking it worked
head(tax_table(physeq.f)) #just checking it worked
physeq.f.ra <- transform_sample_counts(physeq.f, function(x) x*100/sum(x)) #transform data from raw abundance to relative abundance
physeq.f.ra.ord <- tax_glom(physeq.f.ra, "Class",NArm=FALSE) #merge taxa on the class level, so that there's only 1 value for each Class CHANGE HERE IF YOU WANT A DIFFERENT TAXONOMIC LEVEL
propData <- as.data.frame((otu_table(physeq.f.ra.ord))) #make otu table a dataframe
plotDF1 <- propData %>% #within the propData variable
  rownames_to_column(var="taxa") %>% 
  melt() %>% 
  magrittr::set_names(c("sample", "taxa", "relab"))
head(plotDF1)#just checking it worked
taxonomy.2 <- tax_table(physeq.f) %>%
  as.data.frame() %>%
  rownames_to_column(var="taxa")
head(taxonomy.2)#just checking it worked
head(plotDF1)#just checking it worked
plotDF1 <- left_join(plotDF1, taxonomy.2, by="taxa") %>% select(taxa, sample, relab, Class) #combine dataframes merging by taxa, with the columns listed in select. ALSO CHANGE CLASS HERE IF YOU WANT A DIFFERENT TAXONOMIC RANK
head(plotDF1)#just checking it worked
length(levels(factor(plotDF$Class))) #check how many classes there are
mycolors <- c("black","red","orange","yellow","green","blue","magenta","darkorchid4") #make a list of colors the same length as the number of classes
names(mycolors)<-levels(factor(plotDF$Class)) #set the colors to an associated taxonomic rank. ALSO CHANGE CLASS HERE IF YOU WANT A DIFFERENT TAXONOMIC RANK
mycolors #confirm it worked
sampdata<-data.frame(sample_data(physeq.f)) #make dataframe of the sample data
metadata.2 <- sampdata %>%
  rownames_to_column(var="sample")
metadata.2
plotDF1 <- left_join(plotDF1, metadata.2, by="sample") #combine plotDF1 and metadata.2 by sample name
head(plotDF1) #just checking it worked
length(levels(factor(plotDF1$Class))) #check how many classes there are. ALSO CHANGE CLASS HERE IF YOU WANT A DIFFERENT TAXONOMIC RANK
plotDF1$Class<-factor(plotDF1$Class) #make class a factor. ALSO CHANGE CLASS HERE IF YOU WANT A DIFFERENT TAXONOMIC RANK
plotDF1$sample<-factor(plotDF1$sample) #make sample a factor
plotDF1$Site<-factor(plotDF1$Region) #make Region a factor
ggplot(plotDF1, aes(x=plotDF1$sample, relab, fill=Class)) + #make a plot with genotype/sample name on the x-axis, relative abundance on the y-axis, and color filled by Class. ALSO CHANGE CLASS HERE IF YOU WANT A DIFFERENT TAXONOMIC RANK
  geom_bar(stat="identity", position = "stack") + #make it a barplot with classes stacked on top of each other
  theme(axis.text.x = element_text(angle = 90,size = 10)) + #set x-axis labels to be oriented vertically, and set the size of the text to 10
  scale_fill_manual(values = mycolors,limits = levels(plotDF$Class)) + #set the colors being filled in by class to the mycolors variable made earlier
  facet_grid(~Region,space="free_x",scales="free_x",drop=TRUE) + #facet wrap (separate out) by Region
  theme(legend.title = element_text(size = 8),legend.text = element_text(size = 6),legend.position = "bottom") #set legent title size to 8 and legend text size to 6
```


## Bubble plots
What goes in:
What goes out:
ASVs pulled from simper
```{r}
physeq.f.ra <- transform_sample_counts(ps, function(x) x*100/sum(x))
p<-merge_samples(physeq.f.ra,"Region")
o<-otu_table(p)
rowSums(otu_table(physeq.f.ra))
propData <- as.data.frame(o)
t<-data.frame(cbind(levels(as.factor(sample_data(ps)$Region))))
t <-cbind(t,propData$ASV_2,propData$ASV_3,propData$ASV_4)
colnames(t)<-c("Region","ASV_2","ASV_3","ASV_4")
pcm = melt(t, id = c("Region")) #convert data frame from a "wide" format to a "long" format
xx = ggplot(pcm, aes(x = Region, y = variable,fill=variable)) + geom_point(aes(size = as.numeric(value)), alpha = 0.75, shape = 21) +  scale_size_continuous(limits = c(0.000001, 100), range = c(.5,10), breaks = c(1,25,50,75)) +  labs( x= "", y = "", size = "Abundance", fill = "Region")  +  theme(legend.key=element_blank(), axis.text.x = element_text(colour = "black", size = 12, face = "bold", angle = 90, vjust = 0.3, hjust = 1), axis.text.y = element_text(colour = "black", face = "bold", size = 11), legend.text = element_text(size = 10, face ="bold", colour ="black"), legend.title = element_text(size = 12, face = "bold"), panel.background = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1.2), legend.position = "right") + scale_y_discrete(limits = rev(levels(pcm$variable)))
xx
```

